### ISSUE TITLE
This repo is not a template, but https://github.com/jpawlowski/mta-sts.template is

### ISSUE THREAD

**Issue by crmne** [forwardemail/mta-sts.forwardemail.net#1]
In the README, it is stated that this repo is a template, but it doesn't show up as such, while the [original repo](https://github.com/jpawlowski/mta-sts.template) is

**Comment by titanism** [comment]
that is an artifact from being generated from that template, non-issue

**Comment by titanism** [comment]
PR welcome if you want to update README.md with a new link / text! 🙏
